version: 2

sources: 
  - name: raw 
    schema: gz_raw_data 
    description: raw_data_tables 
    tables:
    - name: sales
      identifier: raw_gz_sales
      description: sales_d 
    - name: product
      identifier: raw_gz_product
      description: product_d
      columns:
        - name: products_id
          description: PK
          tests:
            - unique 
            - not_null
                
    - name: ship
      identifier: raw_gz_ship
      description: ship_d
      columns:
        - name: orders_id
          description: pk
          tests:
            - unique
            - not_null 